export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const API_CALL_STARTED = 'API_CALL_STARTED';
export const API_CALL_FAIL = 'API_CALL_FAIL';
